### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by mpryor** [notree-md/notree#35]
Notree needs a logo! 

There are some things to consider with the logo:
- Color palette
- Simplicity
- How easy it is to remember
- How unique it is

Once we've agreed on a logo, we should:

- [ ] update the branding on the readme for notree and add the logo in
- [ ] update the org "avatar" in Github

**Comment by mpryor** [comment]
I'm going to throw out some options here, and we can collaborate to pick which specific options we like, or which themes we like and then iterate

**Comment by mpryor** [comment]
1. ![flat](https://github.com/notree-md/notree/assets/3487369/9b9a1d95-9d4b-4678-98dd-675429169b82)
1. ![minimal-flat-vector-logo-of-a-minimal-tree-of-knowledge-purple-palette-](https://github.com/notree-md/notree/assets/3487369/a0582ad5-4dc0-4a38-a364-ed7eec07ed09)
1. <img src="https://github.com/notree-md/notree/assets/3487369/6eeac2c2-b1a3-4ca5-b9b5-001b8283d106" width="500px"/>

**Comment by mpryor** [comment]
@jollyjerr 
I generated a few ideas above, let me know if you like any in idea or execution, and we can iterate. I'm stuck on a purple palette for some reason but if you're picturing a different color/palette system let me know!

**Comment by jollyjerr** [comment]
omg I LOVE all of these <img width="626" alt="Screenshot 2023-07-10 at 4 24 35 PM" src="https://github.com/notree-md/notree/assets/51095001/5c40a0cb-1178-4823-95b7-b6409054fb93">

**Comment by mpryor** [comment]
Let's roll forward w/ this one:

![](https://user-images.githubusercontent.com/3487369/252477447-7b281845-b3ef-4af7-8af5-d6e81f2eaa90.png)
